apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      ports:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        - hostPort: 8080
        - targetPort: 8080
        - port: 8080
