# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-1.6.4
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-09-20T22:23:19Z"
  labels:
    app: playground
  name: playground
spec:
  containers:
  - command:
    - nginx
    - -g
    - daemon off;
    image: docker.io/library/nginx:latest
    name: nginx
    ports:
    - containerPort: 80
      hostPort: 8080
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /etc/nginx/conf.d:Z
      name: home-blue-nginx-proxy-pod-nginx-conf.d
    workingDir: /
  - command:
    - mongod
    env:
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: secret
    - name: MONGO_INITDB_ROOT_USERNAME
      value: mongoadmin
    - name: MONGO_INITDB_DATABASE
      value: admin
    image: localhost/mongo:custom
    name: mongo
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    stdin: true
    tty: true
    workingDir: /
  - command:
    - catalina.sh
    - run
    image: localhost/tomcat:custom
    name: tomcat
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    volumeMounts:
    - mountPath: /usr/local/tomcat/conf/tomcat-users.xml:Z
      name: home-blue-nginx-proxy-pod-tomcat-tomcat-users.xml
    - mountPath: /usr/local/tomcat/conf/context.xml:Z
      name: home-blue-nginx-proxy-pod-tomcat-context.xml
    workingDir: /usr/local/tomcat
  - command:
    - uvicorn
    - main:app
    - --reload
    - --root-path
    - /api
    image: localhost/fastapi:latest
    name: fastapi
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /app:Z
      name: home-blue-nginx-proxy-pod-python-api-app
    workingDir: /app
  volumes:
  - hostPath:
      path: /home/blue/nginx-proxy-pod/nginx/conf.d
      type: Directory
    name: home-blue-nginx-proxy-pod-nginx-conf.d
  - hostPath:
      path: /home/blue/nginx-proxy-pod/tomcat/tomcat-users.xml
      type: File
    name: home-blue-nginx-proxy-pod-tomcat-tomcat-users.xml
  - hostPath:
      path: /home/blue/nginx-proxy-pod/tomcat/context.xml
      type: File
    name: home-blue-nginx-proxy-pod-tomcat-context.xml
  - hostPath:
      path: /home/blue/nginx-proxy-pod/python-api/app
      type: Directory
    name: home-blue-nginx-proxy-pod-python-api-app
status: {}

