# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-1.6.4
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-09-19T21:26:09Z"
  labels:
    app: playground
  name: playground
spec:
  containers:
  - command:
    - /bin/bash
    - -c
    - mv /usr/local/tomcat/webapps /usr/local/tomcat/webapps2; mv /usr/local/tomcat/webapps.dist
      /usr/local/tomcat/webapps; catalina.sh run
    image: docker.io/library/tomcat:latest
    name: tomcat
    ports:
    - containerPort: 80
      hostPort: 8080
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    volumeMounts:
    - mountPath: /usr/local/tomcat/webapps.dist/manager/META-INF/context.xml:Z
      name: home-blue-nginx-proxy-pod-tomcat-context.xml
    - mountPath: /usr/local/tomcat/conf/tomcat-users.xml:Z
      name: home-blue-nginx-proxy-pod-tomcat-tomcat-users.xml
    workingDir: /usr/local/tomcat
  - command:
    - flask
    - run
    - --host
    - 0.0.0.0
    env:
    - name: FLASK_DEBUG
      value: "1"
    - name: FLASK_APP
      value: app.py
    - name: FLASK_ENV
      value: development
    image: localhost/test:latest
    name: flask
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    volumeMounts:
    - mountPath: /app:Z
      name: home-blue-nginx-proxy-pod-python-api-app
    workingDir: /app
  - command:
    - nginx
    - -g
    - daemon off;
    image: docker.io/library/nginx:latest
    name: nginx
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    volumeMounts:
    - mountPath: /etc/nginx/conf.d:Z
      name: home-blue-nginx-proxy-pod-nginx-conf.d
    - mountPath: /usr/share/nginx/html:Z
      name: home-blue-nginx-proxy-pod-nginx-html
    workingDir: /
  volumes:
  - hostPath:
      path: /home/blue/nginx-proxy-pod/tomcat/context.xml
      type: File
    name: home-blue-nginx-proxy-pod-tomcat-context.xml
  - hostPath:
      path: /home/blue/nginx-proxy-pod/tomcat/tomcat-users.xml
      type: File
    name: home-blue-nginx-proxy-pod-tomcat-tomcat-users.xml
  - hostPath:
      path: /home/blue/nginx-proxy-pod/python-api/app
      type: Directory
    name: home-blue-nginx-proxy-pod-python-api-app
  - hostPath:
      path: /home/blue/nginx-proxy-pod/nginx/conf.d
      type: Directory
    name: home-blue-nginx-proxy-pod-nginx-conf.d
  - hostPath:
      path: /home/blue/nginx-proxy-pod/nginx/html
      type: Directory
    name: home-blue-nginx-proxy-pod-nginx-html
status: {}

